package com.project15.server.exception;

import lombok.Getter;

public enum ExceptionCode {
    MEMBER_NOT_FOUND,
    ITEM_NOT_FOUND,
    IMAGE_NOT_FOUND,
    BID_NOT_FOUND,
    CHAT_ROOM_NOT_FOUND,
    MESSAGE_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    WISH_NOT_FOUND,
    MEMBER_EXISTS,
    ITEM_EXISTS,
    IMAGE_EXISTS,
    BID_EXISTS,
    CHAT_ROOM_EXISTS,
    MESSAGE_EXISTS,
    CATEGORY_EXISTS,
    STATUS_EXIST,
    WISH_EXIST,
    IMAGE_UPLOAD_FAIL,
    SELLER_MISS_MATCH,
    BID_UNIT_INVALID,
    SELLER_CAN_NOT_BIDDING,
    BUY_NOW_UNAVAILABLE,
    NOT_ON_AUCTION,
    NOT_IN_WAITING
}
