spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project015?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 816174135962-4a5jp5ci125pdsv68qvg7k1o9ju5mn0r.apps.googleusercontent.com
            client-secret: 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
            scope: email

          naver:
            client-id: RcQw2zGUHcfPsxPPI8Pl
            client-secret: RiUPtY21Ob
            redirect-uri: http://project015-bucket.s3-website.ap-northeast-2.amazonaws.com
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: 701278fda85d0939a112f3d73f9f3cc8
            client-secret: I7OA1M9yh0Lnh9ajf705PxwhGCqXxAkB
            redirect-uri: http://project015-bucket.s3-website.ap-northeast-2.amazonaws.com
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucketName: project015-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
    header: Authorization
    secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
    token-validity-in-seconds: 86400
